package edu.pjatk.jcarsapi.car;

public enum Model {
    //TOYOTA:
    COROLLA, CAMRY, RAV4, PRIUS, HILUX, YARIS, TACOMA, SIENNA,
    //HONDA:
    CIVIC, ACCORD, CR_V, HR_V, PILOT, ODYSSEY, FIT,
    //NISSAN:
    ALTIMA, SENTRA, ROGUE, PATHFINDER, MAXIMA, FRONTIER,
    //MAZDA:
    MAZDA3, MAZDA6, CX_5, MX_5_MIATA, CX_9,
    //SUBARU:
    IMPREZA, FORESTER, OUTBACK, CROSSTREK, WRX,
    //MITSUBISHI:
    OUTLANDER, ECLIPSECROSS, MIRAGE, LANCER,
    //SUZUKI:
    SWIFT, VITARA, JIMNY,
    //LEXUS:
    RX, ES, NX, IS, GX, LX,
    //ACURA:
    MDX, RDX, TLX, ILX, RLX,
    //INFINITI:
    Q50, Q60, QX50, QX60, QX80,

}
