spring:
  datasource:
    username: admin
    password: password
    url: jdbc:mysql://localhost:3306/jcars
  security:
    user:
      password: "Test12345_"
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  api-docs:
    path: /api-docs