spring:
  datasource:
    username: admin
    password: password
    url: jdbc:postgresql://localhost:5332/jcars
  jpa:
    hibernate:
      ddl-auto: validate
springdoc:
  api-docs:
    path: /api-docs